version: '3.7'

services:

  theseus-ingress:
    build: ingress
    depends_on:
      - theseus-front
    restart: always

  theseus-front:
    build: frontend
    command: npm start
    restart: always
    volumes:
      - theseus_data:/usr/src/app

#  theseus-backend:
#    build: ./backend
#    restart: always
#    command: catalina.sh run
#    environment:
#      PGHOST: theseus-db
#      PGPORT: 5432
#      PGUSER: postgres
#      PGPASSWORD: PGpasswordTheseus
#      PGDATABASE: theseusDB

  theseus-db:
    image: postgres:latest
    volumes:
      - theseusDB:/var/lib/postgresql/data
    restart: always
    environment:
      PGPASSWORD: PGpasswordTheseus

volumes:
  theseusDB:
  theseus_data:

networks:
  default:
    external:
      name: nginx_http-net